// factories/ai-radar/digest.ts
//
// Markdown digest renderer. Pure function: takes items + run summary,
// returns a markdown string. The caller writes to disk.
//
// Section ordering matches the handoff spec:
//   1. Upgrade candidates    (recommendedAction = open_upgrade_pr | update_model_policy)
//   2. Research candidates   (recommendedAction = investigate | create_eval)
//   3. Memory-only items     (recommendedAction = remember | update_skill)
//   4. Ignored / low signal  (recommendedAction = ignore)
//   5. Security review       (recommendedAction = security_review)
//   6. Run summary           (per-source table + final classification)
//
// PR #8 emits only "remember" items, so sections 1, 2, 4, 5 render
// empty placeholders. PR #9's classifier populates the rest.

import type { RadarItem, RecommendedAction, RunSummary } from "./types.ts";

export interface RenderDigestInput {
  date: string;
  items: RadarItem[];
  summary: RunSummary;
}

interface Section {
  heading: string;
  match: (a: RecommendedAction) => boolean;
  emptyText: string;
}

const SECTIONS: Section[] = [
  {
    heading: "Upgrade candidates",
    match: (a) => a === "open_upgrade_pr" || a === "update_model_policy",
    emptyText: "_None this run._",
  },
  {
    heading: "Research candidates",
    match: (a) => a === "investigate" || a === "create_eval",
    emptyText: "_None this run._",
  },
  {
    heading: "Memory-only items",
    match: (a) => a === "remember" || a === "update_skill",
    emptyText: "_None this run._",
  },
  {
    heading: "Ignored / low signal",
    match: (a) => a === "ignore",
    emptyText: "_None this run._",
  },
  {
    heading: "Security review",
    match: (a) => a === "security_review",
    emptyText: "_None this run._",
  },
];

export function renderDigest(input: RenderDigestInput): string {
  const { date, items, summary } = input;
  const lines: string[] = [];
  const itemWord = items.length === 1 ? "item" : "items";

  lines.push(`# AI Radar Digest — ${date}`);
  lines.push("");
  lines.push(
    `_Generated by \`factories/ai-radar\` at ${summary.finishedAt} ` +
      `(mode: ${summary.mode}, run ${summary.runId})._`,
  );
  lines.push("");
  lines.push(
    `**${items.length} ${itemWord}** observed across ` +
      `**${summary.perSource.length} sources**. ` +
      `v0 emits \`remember\` by default; richer classification lands in PR #9.`,
  );
  lines.push("");

  for (const section of SECTIONS) {
    lines.push(`## ${section.heading}`);
    lines.push("");
    const sectionItems = items.filter((i) =>
      section.match(i.recommendedAction),
    );
    if (sectionItems.length === 0) {
      lines.push(section.emptyText);
      lines.push("");
      continue;
    }
    renderItemsBySource(lines, sectionItems);
  }

  lines.push("## Run summary");
  lines.push("");
  if (summary.perSource.length === 0) {
    lines.push("_No sources fetched._");
    lines.push("");
  } else {
    lines.push("| Source | Status | New | Seen | HTTP | Bytes | Error |");
    lines.push("|---|---|---:|---:|---:|---:|---|");
    for (const s of summary.perSource) {
      lines.push(
        `| ${escapeCell(s.id)} | ${s.classification} | ${s.newItems} | ` +
          `${s.seenItems} | ${s.httpStatus ?? "—"} | ${s.fetchedBytes} | ` +
          `${s.error ? escapeCell(s.error) : "—"} |`,
      );
    }
    lines.push("");
  }
  lines.push(`**Final**: ${summary.finalClassification}`);
  if (summary.killSwitchActive) {
    lines.push("");
    lines.push("> Kill switch is active. No artifacts written.");
  }
  lines.push("");

  return lines.join("\n");
}

function renderItemsBySource(lines: string[], items: RadarItem[]): void {
  const groups = new Map<string, RadarItem[]>();
  for (const item of items) {
    const key = item.source.id;
    const list = groups.get(key) ?? [];
    list.push(item);
    groups.set(key, list);
  }

  // Sort source groups by trust tier ascending (official first), then by name.
  const tierRank: Record<string, number> = {
    official: 0,
    maintainer: 1,
    community: 2,
    rumor: 3,
  };
  const sortedGroups = [...groups.entries()].sort(([, a], [, b]) => {
    const ta = tierRank[a[0]!.source.trustTier] ?? 99;
    const tb = tierRank[b[0]!.source.trustTier] ?? 99;
    if (ta !== tb) return ta - tb;
    return a[0]!.source.name.localeCompare(b[0]!.source.name);
  });

  for (const [, groupItems] of sortedGroups) {
    const head = groupItems[0]!;
    lines.push(`### ${head.source.name} (${head.source.trustTier})`);
    lines.push("");
    // Sort items within a group by publishedAt desc, then title asc.
    const sorted = [...groupItems].sort((a, b) => {
      const ad = a.publishedAt ?? "";
      const bd = b.publishedAt ?? "";
      if (ad !== bd) return bd.localeCompare(ad);
      return a.title.localeCompare(b.title);
    });
    for (const item of sorted) {
      lines.push(formatItemLine(item));
    }
    lines.push("");
  }
}

function formatItemLine(item: RadarItem): string {
  const titleLink = `[${escapeMd(item.title)}](${item.source.url})`;
  const date = item.publishedAt ? ` _(${item.publishedAt.slice(0, 10)})_` : "";
  return `- ${titleLink}${date}\n  - ${escapeMd(item.summary)}`;
}

function escapeMd(s: string): string {
  // Conservative: just collapse newlines so markdown bullets stay intact.
  return s.replace(/\r?\n+/g, " ").trim();
}

function escapeCell(s: string): string {
  // Markdown table cell: escape pipes and remove newlines.
  return s.replace(/\|/g, "\\|").replace(/\r?\n+/g, " ");
}
